const express = require('express');
const app = express();

// Define your routes and middleware here

module.exports.handler = async (event, context) => {
  // Pass the incoming request to your Express app
  const result = await serverlessExpress({
    app,
    event,
    context,
  });

  // Return the response generated by your Express app
  return result;
};